import { LoginStateEnum } from "@propel-auth-fern/fe_v2-client/resources";
import { Dispatch, MouseEvent, ReactNode, SetStateAction, SyntheticEvent, useState } from "react";
import { useClient } from "../state/useClient";
import { ElementAppearance, useConfig } from "../state";
import {
  Alert,
  Container,
  Image,
  Input,
  Button,
  H3,
  Paragraph,
  AlertProps,
  ContainerProps,
  ImageProps,
  InputProps,
  ButtonProps,
  H3Props,
  ParagraphProps,
} from "../elements";
import { BAD_REQUEST_MFA_VERIFY, FORBIDDEN, NOT_FOUND_MFA_VERIFY, UNEXPECTED_ERROR } from "./shared/constants";

export type VerifyProps = {
  setStep: Dispatch<SetStateAction<LoginStateEnum>>;
  appearance?: VerifyAppearance;
};

export type VerifyAppearance = {
  options?: {
    headerContent?: ReactNode;
    displayLogo?: boolean;
    submitButtonContent?: ReactNode;
  };
  elements?: {
    Container?: ElementAppearance<ContainerProps>;
    Logo?: ElementAppearance<ImageProps>;
    Header?: ElementAppearance<H3Props>;
    InstructionText?: ElementAppearance<ParagraphProps>;
    CodeInput?: ElementAppearance<InputProps>;
    SubmitButton?: ElementAppearance<ButtonProps>;
    CodeTypeLink?: ElementAppearance<ButtonProps>;
    ErrorMessage?: ElementAppearance<AlertProps>;
  };
};

export const Verify = ({ setStep, appearance }: VerifyProps) => {
  const { config } = useConfig();
  const { mfaApi } = useClient();
  const [loading, setLoading] = useState(false);
  const [code, setCode] = useState("");
  const [useBackupCode, setUseBackupCode] = useState(false);
  const [error, setError] = useState<string | undefined>(undefined);

  const codeLabel = `Enter the 6 digit code generated by your authenticator app:`;
  const backupCodeLabel = `Enter an unused backup code:`;
  const inputLabel = useBackupCode ? backupCodeLabel : codeLabel;

  const codeButtonText = `Enter a code from your authenticator app`;
  const backupCodeButtonText = `Lost your device? Enter a backup code`;
  const buttonText = useBackupCode ? codeButtonText : backupCodeButtonText;

  function toggleCodeType(e: MouseEvent<HTMLButtonElement>) {
    e.preventDefault();
    setCode("");
    setError(undefined);
    setUseBackupCode(!useBackupCode);
  }

  async function verifyMfa(e: SyntheticEvent) {
    try {
      e.preventDefault();
      setLoading(true);
      setError(undefined);
      const response = await mfaApi.mfaVerify({ code });
      if (response.ok) {
        setStep(response.body);
      } else {
        response.error._visit({
          badRequestMfaVerify: () => setError(BAD_REQUEST_MFA_VERIFY),
          notFoundMfaVerify: () => setError(NOT_FOUND_MFA_VERIFY),
          forbiddenMfaVerify: () => setError(FORBIDDEN),
          _other: () => setError(UNEXPECTED_ERROR),
        });
      }
    } catch (e) {
      setError(UNEXPECTED_ERROR);
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div data-contain="component">
      <Container appearance={appearance?.elements?.Container}>
        {appearance?.options?.displayLogo && (
          <div data-contain="logo">
            <Image src={config.logo_url} alt={config.site_display_name} appearance={appearance?.elements?.Logo} />
          </div>
        )}
        <div data-contain="header">
          <H3 appearance={appearance?.elements?.Header}>{appearance?.options?.headerContent || "Verify"}</H3>
        </div>
        <div data-contain="form">
          <form onSubmit={verifyMfa}>
            <Paragraph appearance={appearance?.elements?.InstructionText}>{inputLabel}</Paragraph>
            <div>
              <Input
                type={"text"}
                placeholder={"123456"}
                value={code}
                onChange={(e) => setCode(e.target.value)}
                appearance={appearance?.elements?.CodeInput}
              />
            </div>
            <Button loading={loading} appearance={appearance?.elements?.SubmitButton}>
              {appearance?.options?.submitButtonContent || "Submit"}
            </Button>
            {error && (
              <Alert appearance={appearance?.elements?.ErrorMessage} type={"error"}>
                {error}
              </Alert>
            )}
          </form>
        </div>
        <div data-contain="link">
          <Button onClick={toggleCodeType} appearance={appearance?.elements?.CodeTypeLink}>
            {buttonText}
          </Button>
        </div>
      </Container>
    </div>
  );
};
